---
base_config:
    values:
        PORT: 5000
        WEBAPP_CELERY_BACKEND_USE_SSL: 0
        WEBAPP_CELERY_BROKER_CONNECTION_TIMEOUT: 30
        WEBAPP_CELERY_BROKER_USE_SSL: 0
        WEBAPP_CELERY_TRACK_STARTED: 1
        WEBAPP_LOG_FORMAT_JSON: 1
        WEBAPP_LOG_WITH_TIMESTAMPS: 0
        WEBAPP_PORT: 5000
    memory: {}
    cpu: {}
    tags: {}
    registry: {}
    healthcheck:
        web/cmd:
            readinessProbe:
                timeoutSeconds: 5
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                httpGet:
                    path: /v1/status
                    port: 5000
                failureThreshold: 3

per_app_values:
    "dev-webapp":
        WEBAPP_BASE_URL: https://ds-playground.careotter.com
        WEBAPP_HOST: ds-playground.careotter.com
        WEBAPP_LOG_LEVEL: DEBUG
    "prod-webapp":
        WEBAPP_LOG_LEVEL: INFO

per_app_config:
    "dev-webapp":
        healthcheck:
            web/cmd:
                readinessProbe:
                    timeoutSeconds: 5
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    successThreshold: 1
                    httpGet:
                        path: /v1/status
                        port: 5000
                    failureThreshold: 3
    "prod-webapp":
        # This is just an example, production should have healthchecks too
        healthcheck: {}

values_from_env:
    - "WEBAPP_BASE_URL"
    - "WEBAPP_CELERY_BROKER_URL"
    - "WEBAPP_CELERY_RESULT_BACKEND"
